// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_section: dynamic(() => import("./CtaSection")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  hero_section: dynamic(() => import("./HeroSection")),
};
